[package]
name = "xmpegts"
description = "mpegts library."
version = "0.2.0"
authors = ["HarlanC <wawacry@qq.com"]
repository = "https://github.com/harlanc/xiu"
license = "MIT"
readme = "README.md"
categories = ["multimedia", "multimedia::video", 'multimedia::audio']
keywords = ["mpegts", "video", "streaming"]
edition = "2018"

[dependencies]
byteorder = "1.5.0"
bytes = "1.11.1"
failure = "0.1.8"
bytesio = { path = "../../bytesio/" }
