[package]
name = "commonlib"
version = "0.1.1"
authors = ["HarlanC <wawacry@qq.com>"]
edition = "2018"
description = "a common library for xiu project."
license = "MIT"
repository = "https://github.com/harlanc/xiu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
env_logger = "0.11.9"
job_scheduler_ng = "2.4.0"
chrono = "0.4"
failure = "0.1.8"
log = "0.4.29"
indexmap = "2.13.0"
md5 = "0.8.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
