[package]
name = "xflv"
description = "flv library."
version = "0.3.0"
authors = ["HarlanC <wawacry@qq.com"]
repository = "https://github.com/harlanc/xiu"
license = "MIT"
readme = "README.md"
categories = ["flv"]
keywords = ["flv", "video", "streaming"]
edition = "2018"

[dependencies]
byteorder = "1.5.0"
bytes = "1.11.1"
failure = "0.1.8"
serde = { version = "1.0", features = ["derive", "rc"] }
log = "0.4"
indexmap = "2.13.0"

bytesio = { path = "../../bytesio/" }
h264-decoder = { path = "../../codec/h264/" }
