name: Build/publish release

#on: [push, pull_request]
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*" # Push events to every tag not containing /

jobs:
  release:
    name: Binary ${{ matrix.target }} (on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    strategy:
      matrix:
        include:
          # supported
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            compress: true
            cargo_flags: ""

          # supported
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            compress: true
            cargo_flags: ""

          #- os: ubuntu-latest
          #  target: aarch64-unknown-linux-musl
          #  compress: true
          #  cargo_flags: ""

          # supported
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            compress: true
            cargo_flags: ""

          #- os: ubuntu-20.04
          #  target: armv7-unknown-linux-musleabihf
          #  compress: true
          #  cargo_flags: ""

          # supported
          - os: ubuntu-22.04
            target: armv7-unknown-linux-gnueabihf
            compress: true
            cargo_flags: ""

          #- os: ubuntu-latest
          #  target: arm-unknown-linux-musleabihf
          #  compress: true
          #  cargo_flags: ""

          ##- os: ubuntu-latest
          ##  target: riscv64gc-unknown-linux-gnu
          ##  compress: false
          ##  cargo_flags: "--no-default-features"

          # supported
          #- os: windows-latest
          #  target: x86_64-pc-windows-msvc
          #  compress: true
          #  cargo_flags: ""

          # supported
          #- os: windows-latest
          #  target: i686-pc-windows-msvc
          #  compress: true
          #  cargo_flags: ""

          # # supported
          # - os: ubuntu-22.04
          #  target: x86_64-apple-darwin
          #  compress: true
          #  cargo_flags: ""

          ## - os: macos-latest
          ##   target: aarch64-apple-darwin
          ##   compress: false
          ##   cargo_flags: ""

          # supported
          #- os: ubuntu-latest
          #  target: x86_64-unknown-freebsd
          #  compress: false
          #  cargo_flags: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: sudo apt install cmake clang musl-tools pkg-config libssl-dev gcc-multilib libopus-dev
        if: startsWith(matrix.os, 'ubuntu')

      - name: Set up project
        run: |
          export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig/
          echo $PKG_CONFIG_PATH
          find /usr/lib -name openssl.pc
          #cat /usr/lib/x86_64-linux-gnu/pkgconfig/openssl.pc
          #dpkg -l | grep openssl

          #/usr/lib/x86_64-linux-gnu/pkgconfig/openssl.pc
        if: startsWith(matrix.os, 'ubuntu')

      - name: cargo build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          working-directory: ./application/xiu
          args: --release --locked ${{ matrix.cargo_flags }}
          target: ${{ matrix.target }}

      - name: Set exe extension for Windows
        run: echo "EXE=.exe" >> $env:GITHUB_ENV
        if: startsWith(matrix.os, 'windows')

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          files: target/${{ matrix.target }}/release/xiu${{ env.EXE }}
          args: --best --lzma
          strip: false # We're stripping already in Cargo.toml
        if: ${{ matrix.compress }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/xiu${{ env.EXE }}

      - name: Get version from tag
        id: extract_version
        run: |
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/xiu${{ env.EXE }}
          tag: ${{ github.ref_name }}
          asset_name: xiu-${{ steps.extract_version.outputs.version }}-${{ matrix.target }}${{ env.EXE }}
        if: startsWith(github.ref_name, 'v') && github.ref_type == 'tag'

  # Build docker images and upload to docker hub
  container-images:
    name: Publish images
    runs-on: ubuntu-latest
    needs: release
    # Run for tags and pushes to the default branch
    if: (startsWith(github.ref_name, 'v') && github.ref_type == 'tag') || github.event.repository.default_branch == github.ref_name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact aarch64-unknown-linux-gnu
        uses: actions/download-artifact@v4
        with:
          name: aarch64-unknown-linux-gnu
          path: target/aarch64-unknown-linux-gnu/release

      - name: Download artifact x86_64-unknown-linux-gnu
        uses: actions/download-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release

      - name: Download artifact armv7-unknown-linux-gnueabihf
        uses: actions/download-artifact@v4
        with:
          name: armv7-unknown-linux-gnueabihf
          path: target/armv7-unknown-linux-gnueabihf/release

      #- name: Download artifact aarch64-unknown-linux-musl
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: aarch64-unknown-linux-musl
      #    path: target/aarch64-unknown-linux-musl/release

      #- name: Download artifact x86_64-unknown-linux-musl
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: x86_64-unknown-linux-musl
      #    path: target/x86_64-unknown-linux-musl/release

      #- name: Download artifact armv7-unknown-linux-musleabihf
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: armv7-unknown-linux-musleabihf
      #    path: target/armv7-unknown-linux-musleabihf/release
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            ghcr.io/nikitos/tusd
          tags: |
            type=sha
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            GIT_VERSION=${{ env.GIT_VERSION }}
            GIT_COMMIT=${{ github.sha }}
          platforms: linux/amd64,linux/arm64/v8

      #- name: podman build linux/arm64 (alpine edition)
      #  run: podman build --format docker --platform linux/arm64/v8 --manifest myexe-alpine -f Containerfile.alpine target/aarch64-unknown-linux-musl/release

      #- name: podman build linux/amd64 (alpine edition)
      #  run: podman build --format docker --platform linux/amd64 --manifest myexe-alpine -f Containerfile.alpine target/x86_64-unknown-linux-musl/release

      #- name: podman build linux/arm (alpine edition)
      #  run: podman build --format docker --platform linux/arm/v7 --manifest myexe-alpine -f Containerfile.alpine target/armv7-unknown-linux-musleabihf/release

      #- name: podman manifest push latest (alpine edition)
      #  run: podman manifest push myexe-alpine docker.io/harlancn/myexe:alpine

      #- name: podman manifest push tag version (alpine edition)
      #  run: podman manifest push myexe-alpine docker.io/harlancn/myexe:${{ needs.publish.outputs.version }}-alpine
      #  if: startsWith(github.ref_name, 'v')
